### ISSUE TITLE
Incorrect Item Listing "Grips of the Warrior"

### ISSUE THREAD

**Issue by oneofmanyacdcfanstoo** [reizy/andors-trail-wiki#20]
You have Gloves called "Grips of the Warrior" listed as being sold by Zechariah in Sullengard. I just completed the quest "Recovering Stolen Property" and gave Zechariah back all his stuff. He is able to trade with me and has everything on your list available EXCEPT for the Grips of the Warrior.

**Comment by jgemmajr** [comment]
the grips of the warrior do not appear in the inventory 100% of the time. I did that on purpose. So you are good

**Comment by jgemmajr** [comment]
This can be closed
