### ISSUE TITLE
Incorrect item listing: "Amphibian Gloves"

### ISSUE THREAD

**Issue by oneofmanyacdcfanstoo** [reizy/andors-trail-wiki#21]
The Amphibians Gloves listed as being in elm_drop1 are no longer there in the new version of the game. I don't know if they were there previously,  but they are currently not. I just picked up everything from that spot.... no gloves.

**Comment by NutAndor** [comment]
They still exist in the game without issue - so no bug.
You don't get the same loot every time, it is sometimes random, especially in the Elm mine.
