### ISSUE TITLE
Incorrect Item Listing for Ring of Lesser Shadow

### ISSUE THREAD

**Issue by oneofmanyacdcfanstoo** [reizy/andors-trail-wiki#22]
Ring of Lesser Shadow is listed as Give by Quest by Lovis and Hannah. Neither of them give that ring during a quest, no matter how the Guynmart castle quest is completed.

**Comment by reizy** [comment]
He change **Ring of Shadow** to **Ring of Lesser Shadow**, it's not a reward of Guynmart castle quest
